intent:
    start_radio:
        de:
            unknown_name: ["Den Radiosender oder Songnamen kenne ich nicht."]
            unknown_query: ["Die Anfrage ist leer."]
        en:
            unknown_name: ["I don't know that station or song name."]
            unknown_query: ["The query is empty."]
        radio_station:
            "Deutschlandfunk": "http://st01.dlf.de/dlf/01/64/mp3/stream.mp3"
            "HR 1": "http://hr-hr1-live.cast.addradio.de/hr/hr1/live/mp3/128/stream.mp3"
            "MDR aktuell": "http://mdr-284340-0.cast.mdr.de/mdr/284340/0/mp3/high/stream.mp3"
            "N-JOY": "http://ndr-njoy-live.cast.addradio.de/ndr/njoy/live/mp3/128/stream.mp3"
            "NDR 2": "http://ndr-ndr2-niedersachsen.cast.addradio.de/ndr/ndr2/niedersachsen/mp3/128/stream.mp3"
            "Bremen 1": "http://rb-bremeneins-live.cast.addradio.de/rb/bremeneins/live/mp3/128/stream.mp3"
            "Fritz": "http://fritz.de/livemp3"
            "WDR 1": "http://wdr-1live-live.icecast.wdr.de/wdr/1live/live/mp3/128/stream.mp3"
            "RPR 1": "https://streams.rpr1.de/rpr-simulcast-128-mp3"
            "Transat": "https://n13a-eu.rcs.revma.com/dy09pqzctwzuv?rj-ttl=5&rj-tok=AAABh9PPc-EA5VOxN_isA_41mQ"
            "Trans": "https://n13a-eu.rcs.revma.com/dy09pqzctwzuv?rj-ttl=5&rj-tok=AAABh9PPc-EA5VOxN_isA_41mQ"
            "Ostseewelle": "http://irmedia.streamabc.net/irm-oswsommer-mp3-128-6375323?sABC=6478q422%230%235077q11r068877r547p3qn54no65o960%23&aw_0_1st.playerid=&amsparams=playerid:;skey:1685640226"
        file_name:
            "Do I Wanna Know": "./songs/Do I Wanna Know.wav"
            "Feeling Good": "./songs/Feeling Good.wav"
            "Gorilla": "./songs/Gorilla.mp3"
