intent:
    set_volume:
        de:
            increase_volume_no_message: [""]
            decrease_volume_no_message: [""]
            increase_volume: ["Lautstärke wird erhöht."]
            increase_volume_by_value: ["Lautstärke wird auf {} Prozent erhöht."]
            current_volume: ["Die Lautstärke beträgt {} Prozent."]
            decrease_volume: ["Lautstärke wird verringert."]
            decrease_volume_by_value: ["Lautstärke wird auf {} Prozent verringert."]
            same_volume: ["Lautstärke bereits auf {} Prozent eingestellt."]
            exception: ["Lautstärke konnte nicht angepasst werden"]
            invalid_volume: ["Bitte setze die Lautstärke auf einen Wert zwischen 0 und 10."]
        en:
            increase_volume_no_message: [""]
            decrease_volume_no_message: [""]
            increase_volume: ["Volume is increased."]
            increase_volume_by_value: ["Volume is increased to {} percent."]
            current_volume: ["The current volume is {} percent."]
            decrease_volume: ["Volume is decreased."]
            decrease_volume_by_value: ["Volume is decreased to {} percent."]
            same_volume: ["Volume already set on {} percent."]
            exception: ["Volume could not be modified."]
            invalid_volume: ["Please set the volume to a value betweeen 0 and 10."]

            