intent:
    set_voiceSpeed:
        de:
            increase_voiceSpeed_no_message: [""]
            decrease_voiceSpeed_no_message: [""]
            increase_voiceSpeed: ["Geschwindigkeit wird erhöht."]
            increase_voiceSpeed_by_value: ["Geschwindigkeit wird auf {} erhöht."]
            current_voiceSpeed: ["Die Geschwindigkeit beträgt {}."]
            decrease_voiceSpeed: ["Geschwindigkeit wird verringert."]
            decrease_voiceSpeed_by_value: ["Geschwindigkeit wird auf {} verringert."]
            same_voiceSpeed: ["Geschwindigkeit bereits auf {} eingestellt."]
            exception: ["Geschwindigkeit konnte nicht angepasst werden"]
        en:
            increase_voiceSpeed_no_message: [""]
            decrease_voiceSpeed_no_message: [""]
            increase_voiceSpeed: ["Voice speed is increased."]
            increase_voiceSpeed_by_value: ["Voice speed is increased to {}."]
            current_voiceSpeed: ["The current voice speed is {}."]
            decrease_voiceSpeed: ["voiceSpeed is decreased."]
            decrease_voiceSpeed_by_value: ["Voice speed is decreased to {}."]
            same_voiceSpeed: ["Voice speed already set on {}."]
            exception: ["Voice speed could not be modified."]