intent:
    wiki:
        de:
            unknown_entity: ["Ich weiß nichts über {}.", "{} kenne ich nicht."]
        en:
            unknown_entity: ["I don't know what you mean with {}.", "I don't know {}."]