intent:
    start_radio:
        radio_station:
            "Deutschlandfunk": "https://st01.sslstream.dlf.de/dlf/01/128/mp3/stream.mp3"
            "Bayern 3": "https://dispatcher.rndfnk.com/br/br3/live/aac/low"
            "Bayerischer Rundfunk": "https://dispatcher.rndfnk.com/br/br24/live/aac/low"
            "Mitteldeutscher Rundfunk": "http://mdr-284340-0.cast.mdr.de/mdr/284340/0/mp3/high/stream.mp3"
            "Norddeutscher Rundfunk": "https://icecast.ndr.de/ndr/ndr1niedersachsen/hannover/mp3/128/stream.mp3"
            "Saarländischer Rundfunk": "https://sr.audiostream.io/sr/1009/mp3/128/sr1.mp3"
            "Südwestdeutscher Rundfunk": "https://liveradio.swr.de/sw331ch/swr1bw/"
            "Westdeutscher Rundfunk": "http://wdr-1live-live.icecast.wdr.de/wdr/1live/live/mp3/128/stream.mp3"
            "Nordrhein-Westfahlen": "https://s1-webradio.nrw1.de/nrw1"
            "BR 1": "https://dispatcher.rndfnk.com/br/br24/live/aac/low"
            "MDR 1": "http://mdr-284340-0.cast.mdr.de/mdr/284340/0/mp3/high/stream.mp3"
            "NDR 1": "https://icecast.ndr.de/ndr/ndr1niedersachsen/hannover/mp3/128/stream.mp3"
            "SR 1": "https://sr.audiostream.io/sr/1009/mp3/128/sr1.mp3"
            "SWR 1": "https://liveradio.swr.de/sw331ch/swr1bw/"
            "WDR 1": "http://wdr-1live-live.icecast.wdr.de/wdr/1live/live/mp3/128/stream.mp3"
            "NRW 1": "https://s1-webradio.nrw1.de/nrw1"
            "RBB 88.8": "http://www.radioberlin.de/live"
            "Inforadio": "http://inforadio.de/livemp3"
            "Kultur": "http://rbbkultur.de/livemp3"
            "Radio 1": "http://www.radioeins.de/livemp3" 
            "Antenne Brandenburg": "https://f131.rndfnk.com/ard/rbb/antennebrandenburg/live/mp3/128/stream.mp3?aggregator=radio-de&cid=01FC1WKZSVNEAC1ZMF0TCAEM1Z&sid=2WIm7fmODYdxcFoDuSNA1XxkDIG&token=lNROXFHLbeIZw4_LKv1U57QbRoeGdFcDgMvN3OQ6S2E&tvf=oEeu1jIAixdmMTMxLnJuZGZuay5jb20"
            "Fritz": "http://fritz.de/livemp3"
            "Transat": "https://n13a-eu.rcs.revma.com/dy09pqzctwzuv?rj-ttl=5&rj-tok=AAABh9PPc-EA5VOxN_isA_41mQ"
            "Ostseewelle": "http://irmedia.streamabc.net/irm-oswsommer-mp3-128-6375323?sABC=6478q422%230%235077q11r068877r547p3qn54no65o960%23&aw_0_1st.playerid=&amsparams=playerid:;skey:1685640226"
            "80er Radio": "https://stream.lokalradio.nrw/444zh3f"
            "90er Radio": "https://stream.lokalradio.nrw/444zj53"
            "2000er Radio": "https://stream.lokalradio.nrw/4456vg5"
            "Pop Radio": "https://stream.lokalradio.nrw/444zmhk"
            "HipHop Radio": "https://stream.lokalradio.nrw/44589s3"
            "Rock Radio": "https://stream.lokalradio.nrw/444zxzk"
            "Weihnachts-Radio": "https://stream.lokalradio.nrw/444zpw3"
            "Deutsch Rap Radio": "http://stream.89.0rtl.de/deutsch-rap/mp3-128"
            "Indie Radio": "https://stream.rtlradio.de/indieclassics/mp3-128"
            "Country Radio": "https://stream.rtlradio.de/country/mp3-128"
            "80er": "https://stream.lokalradio.nrw/444zh3f"
            "90er": "https://stream.lokalradio.nrw/444zj53"
            "2000er": "https://stream.lokalradio.nrw/4456vg5"
            "Pop": "https://stream.lokalradio.nrw/444zmhk"
            "HipHop": "https://stream.lokalradio.nrw/44589s3"
            "Rock": "https://stream.lokalradio.nrw/444zxzk"
            "Weihnacht": "https://stream.lokalradio.nrw/444zpw3"
            "Deutsch Rap": "http://stream.89.0rtl.de/deutsch-rap/mp3-128"
            "Indie": "https://stream.rtlradio.de/indieclassics/mp3-128"
            "Country": "https://stream.rtlradio.de/country/mp3-128"
            "Klassik": "https://stream.klassikradio.de/live/mp3-192/liveradio/"
            "Klassik Radio": "https://stream.klassikradio.de/live/mp3-192/liveradio/"
